---
service_name: "{{ dictionary_hosts.dpp_entity_recognition.name }}"
service_img: "{{ dictionary_hosts.dpp_entity_recognition.img }}"
service_tag: "{{ dictionary_hosts.dpp_entity_recognition.tag }}"
service_repo: "{{ dictionary_hosts.dpp_entity_recognition.repo }}"
service_mnt_dir_loc: "{{ docker_mounts_root }}/{{ dictionary_hosts.dpp_entity_recognition.name }}"
service_compose_dir: "{{ docker_compose_root }}/{{ dictionary_hosts.dpp_entity_recognition.name }}"
