---

- name: "{{ service_name }} : Create directories"
  file:
    path: "{{ dir_item }}"
    state: directory
  with_items:
    - "{{ service_mnt_dir_loc }}/logs"
    - "{{ service_mnt_dir_loc }}/conf"
    - "{{ service_mnt_dir_loc }}/tmp"
    - "{{ service_mnt_dir_loc }}/cn-tmp"
    - "{{ service_mnt_dir_loc }}/certs"
  loop_control:
    loop_var: dir_item

- name: "{{ service_name }} : Create directories"
  file:
    path: "{{ dir_item }}"
    state: absent
  with_items:
    - "{{ service_mnt_dir_loc }}"
    - "{{ service_compose_dir }}"
  loop_control:
    loop_var: dir_item
  tags:
    - never
    - remove

- name: "{{ service_name }} : Generate config"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
  with_fileglob:
    - "templates/cn-builder/conf/*.j2"
  loop_control:
    loop_var: conf_item
