---
# tasks file for cn-builder

- name: "Set global vars"
  import_role:
    name: set-global-vars
  tags: 
    - always

- name: "Set local vars"
  include: set-vars.yml
  tags: always

- name: "Stop service"
  import_role:
    name: _docker
    tasks_from: stop

- name: "Install cn_builder"
  include: install-cn-builder.yml
  tags: install

- name: "Start service"
  import_role:
    name: _docker
    tasks_from: start