---
- name: "Create directories"
  file:
    path: "{{ dir_item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ service_mnt_dir_loc }}/tmp"
    - "{{ service_mnt_dir_loc }}/conf"
  loop_control:
    loop_var: dir_item

- name: "Generate config"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0755
  with_fileglob:
    - "templates/plexus-reports/conf/*.j2"
  loop_control:
    loop_var: conf_item
