---

- name: "{{ service_name }} : Create directories"
  file:
    path: "{{ dir_item }}"
    state: directory
    mode: 0644
  with_items:
    - "{{ service_mnt_dir_loc }}/conf"
    - "{{ service_mnt_dir_loc }}/logs"
    - "{{ service_mnt_dir_loc }}/tmp"
  loop_control:
    loop_var: dir_item

- name: "{{ service_name }} : Generate config"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0644
  with_fileglob:
    - "templates/plexus-server/conf/*.j2"
  loop_control:
    loop_var: conf_item
  tags:
    - config

- name: "{{ service_name }} : Generate journal es settings"
  copy:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0644
  with_fileglob:
    - "files/journal-es-settings/*.json"
  loop_control:
    loop_var: conf_item

- name: "{{ service_name }} : Copy static files"
  copy:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename }}"
    mode: 0644
  with_fileglob:
    - "files/plexus-server/*"
  loop_control:
    loop_var: conf_item
  tags:
    - config
