---

- name: "Remove directory"
  file:
    path: "{{ dir_item }}"
    state: absent 
  with_items:
    - "{{ service_mnt_dir_loc }}-{{ '%02d' | format(item) }}"
    - "{{ service_compose_dir }}"
  loop_control:
    loop_var: dir_item
  tags:
    - never
    - remove
    

- name: "Create directory"
  file:
    path: "{{ dir_item }}"
    state: directory 
    mode: 0644
  with_items:
    - "{{ service_mnt_dir_loc }}-{{ '%02d' | format(item) }}/conf"
    - "{{ service_mnt_dir_loc }}-{{ '%02d' | format(item) }}/logs"
  loop_control:
    loop_var: dir_item
  

- name: "Generate configs"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}-{{ '%02d' | format(item) }}/conf/{{ conf_item | basename | regex_replace('.j2$','') }}"
    mode: 0644
  with_fileglob:
    - "templates/conf/*.j2"
  loop_control:
    loop_var: conf_item

