---
- name: 'Create local directory /etc/docker if not exists'
  file:
    path: '/etc/docker'
    state: directory
    mode: "0644"
  notify: restart docker

- name: "Creating '/etc/docker/daemon.json' for unsecure repos"
  template:
    src: daemon.j2
    dest: '/etc/docker/daemon.json'
    mode: "0644"
  notify: restart docker

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Enable Docker API
  lineinfile:
    path: "/usr/lib/systemd/system/docker.service"
    regexp: '^ExecStart'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// -H=tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock'
  notify: restart docker
  when: docker_external_api_enabled

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  # when: docker_restart_on_package_change

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
