---
- name: "Set full template_path"
  set_fact:
    template_path: "{{ 'templates/templates/spell-checker.j2' }}"

- name: "Set vars"
  set_fact:
    template_content: "{{ lookup('template', template_path) }}"
    template_id: "{{ template_path | basename | replace('.j2', '') }}"

- name: "PUT template spell-checker"
  uri:
    url: "http://{{ host.elasticsearch_spell_checker }}:{{ ports.elasticsearch_spell_checker_main }}/_index_template/{{ template_id }}"
    method: "PUT"
    body_format: "json"
    body: "{{ template_content }}"
    validate_certs: false
    status_code:
      - 200
    return_content: true
  register: result_put_template
