---

- name: "Set global vars"
  import_role:
    name: set-global-vars
  tags: 
    - always

- name: "Set vars"
  include_vars: main.yml
  tags:
    - always

- name: "Stop service"
  import_role:
    name: _docker
    tasks_from: stop

- name: "Install DPP-archiver"
  include: "install-dpp-dictionary-enricher.yml"

- name: "Start service"
  import_role:
    name: _docker
    tasks_from: start