---

- name: "Remove directory"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ service_mnt_dir_loc }}"
    - "{{ service_compose_dir }}"
  tags:
    - never
    - remove

- name: "Create directory"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ service_mnt_dir_loc }}/conf"

- name: "Generate config"
  template:
    dest: "{{ service_mnt_dir_loc }}/conf/{{ item | basename | regex_replace('.j2', '') }}"
    src: "{{ item }}"
    mode: 0755
  with_fileglob:
    - "templates/conf/*.j2"
