---
- name: "{{ dictionary_hosts.query_service.name }} : Set Variables"
  set_fact:
    service_name:         "{{ dictionary_hosts.query_service.name }}"
    service_img:          "{{ dictionary_hosts.query_service.img }}"
    service_tag:          "{{ dictionary_hosts.query_service.tag }}"
    service_repo:         "{{ dictionary_hosts.query_service.repo }}"
    service_mnt_dir_loc:  "{{ docker_mounts_root }}/{{ dictionary_hosts.query_service.name }}"
    service_compose_dir:   "{{ docker_compose_root }}/{{ dictionary_hosts.query_service.name }}"