---

- name: "Remove directories"
  file:
    path: "{{ dir_item }}"
    state: absent
  with_items:
    - "{{ service_mnt_dir_loc }}/conf"
    - "{{ service_mnt_dir_loc }}/custom_logo"
    - "{{ service_mnt_dir_loc }}/sites-enabled"
  loop_control:
    loop_var: dir_item
  tags:
    - never
    - remove

- name: "Create directories"
  file:
    path: "{{ dir_item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ service_mnt_dir_loc }}/conf"
    - "{{ service_mnt_dir_loc }}/logs"
    - "{{ service_mnt_dir_loc }}/custom_logo"
    - "{{ service_mnt_dir_loc }}/sites-enabled"
  loop_control:
    loop_var: dir_item

- name: "Generate config"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0755
  with_fileglob:
    - "templates/frontend/conf/*.j2"
  loop_control:
    loop_var: conf_item

- name: "Copy custom_logo"
  copy:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/custom_logo/{{ conf_item | basename }}"
    mode: 0755
  with_fileglob:
    - "files/custom_logo/*"
  loop_control:
    loop_var: conf_item
  when: frontend_custom_logo | default(False)

- name: "Generate sites-enabled"
  template:
    src: "{{ conf_item }}"
    dest: "{{ service_mnt_dir_loc }}/sites-enabled/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0755
  with_fileglob:
    - "templates/frontend/sites-enabled-touchpoint/*{{ frontend_type }}*.j2"
  loop_control:
    loop_var: conf_item
  tags: sites

- name: "Zip externalSettings.js"
  archive:
    path: "{{ service_mnt_dir_loc }}/conf/externalSettings.js"
    dest: "{{ service_mnt_dir_loc }}/conf/externalSettings.js.gz"
    mode: 0755
    format: gz
