---

- name: "WORKER : {{ file_service_cleaner.service_name }} : Create directories"
  file:
    path: "{{ dir_item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ file_service_cleaner.service_mnt_dir_loc }}/conf"
    - "{{ file_service_cleaner.service_mnt_dir_loc }}/crontab"
    - "{{ file_service_cleaner.service_mnt_dir_glfs }}"
  loop_control:
    loop_var: dir_item

- name: "WORKER : {{ file_service_cleaner.service_name }} : Generate config"
  template:
    src: "{{ conf_item }}"
    dest: "{{ file_service_cleaner.service_mnt_dir_loc }}/conf/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0755
  with_fileglob:
    - "templates/file-service-cleaner/conf/*.j2"
  loop_control:
    loop_var: conf_item

- name: "WORKER : {{ file_service_cleaner.service_name }} : Generate crontab"
  template:
    src: "{{ conf_item }}"
    dest: "{{ file_service_cleaner.service_mnt_dir_loc }}/crontab/{{ conf_item | basename | regex_replace('.j2', '') }}"
    mode: 0755
  with_fileglob:
    - "templates/file-service-cleaner/crontab/*.j2"
  loop_control:
    loop_var: conf_item
