---

- name: Set global vars
  import_role:
    name: set-global-vars
  tags: 
    - always

- name: "Set role vars"
  include: set_vars.yml
  tags: always

- name: "Stop service"
  import_role:
    name: _docker
    tasks_from: stop

- name: "Install highlight"
  include: install_highlight.yml
  tags: install

- name: "Start service"
  import_role:
    name: _docker
    tasks_from: start