---
- name: "Check packages"
  package_facts:
    manager: auto

- name: "Check 'nvidia-container-runtime' in packages"
  shell: curl -s -L https://nvidia.github.io/nvidia-container-runtime/centos7/nvidia-container-runtime.repo | sudo tee /etc/yum.repos.d/nvidia-container-runtime.repo
  when: "'nvidia-container-runtime' not in ansible_facts.packages"

- yum:
    name:
      - nvidia-container-runtime
  notify: restart docker
