---
- name: "{{ dictionary_hosts.nginx_file_service.name }} : Set Variables"
  set_fact:
    service_name:         "{{ dictionary_hosts.nginx_file_service.name }}"
    service_img:          "{{ dictionary_hosts.nginx_file_service.img }}"
    service_tag:          "{{ dictionary_hosts.nginx_file_service.tag }}"
    service_repo:         "{{ dictionary_hosts.nginx_file_service.repo }}"
    service_mnt_dir_loc:  "{{ docker_mounts_root }}/{{ dictionary_hosts.nginx_file_service.name }}"
    service_mnt_dir_glfs: "{{ file_service_data_dir }}"
    service_compose_dir:   "{{ docker_compose_root }}/{{ dictionary_hosts.nginx_file_service.name }}"
