---
- name: Set global vars
  import_role:
    name: set-global-vars
  tags:
    always

- name: "Set local vars"
  include_vars: main.yml
  tags:
    - always

- name: "Stop service"
  import_role:
    name: _docker
    tasks_from: stop

- name: "Install service"
  import_tasks:
    file: install_dpp_entity_recognition.yml

- name: "Start service"
  import_role:
    name: _docker
    tasks_from: start
