---
- name: Ensure Pip is installed.
  package:
    name: "{{ pip_package }}"
    state: present

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ pip_item.name | default(item) }}"
    version: "{{ pip_item.version | default(omit) }}"
    virtualenv: "{{ pip_item.virtualenv | default(omit) }}"
    state: "{{ pip_item.state | default(omit) }}"
    extra_args: --ignore-installed
  with_items: "{{ pip_install_packages }}"
  loop_control:
    loop_var: pip_item
